name: release-snapshots

# Publishes snapshot releases of twitter/util, twitter/scrooge, twitter/finagle,
# twitter/twitter-server, and twitter/finatra.
#
# Runs on a cron trigger or manually via a repository dispatch event:
#
# {
#  "event_type": "release-snapshots",
#  "client_payload": {
#    "dry_run": true
#  }
# }
#
env:
  JAVA_OPTS: "-Dsbt.log.noformat=true"
defaults:
  run:
    shell: bash
on:
  repository_dispatch:
    types: [release-snapshots]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run every night at 8AM UTC (1AM PT)
    - cron: '0 8 * * *'

jobs:
  release-snapshots:
    runs-on: ubuntu-latest
    steps:
      - name: dump/context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.8
      - uses: olafurpg/setup-gpg@v3
      - name: checkout/util
        uses: actions/checkout@v2.3.4
        with:
          repository: twitter/util
          ref: develop
          path: util
      - name: checkout/scrooge
        uses: actions/checkout@v2.3.4
        with:
          repository: twitter/scrooge
          ref: develop
          path: scrooge
      - name: checkout/finagle
        uses: actions/checkout@v2.3.4
        with:
          repository: twitter/finagle
          ref: develop
          path: finagle
      - name: checkout/twitter-server
        uses: actions/checkout@v2.3.4
        with:
          repository: twitter/twitter-server
          ref: develop
          path: twitter-server
      - name: checkout/finatra
        uses: actions/checkout@v2.3.4
        with:
          repository: twitter/finatra
          ref: develop
          path: finatra
